# Generated by Django 4.1.12 on 2023-11-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0005_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="progress",
            name="video",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Course.video",
            ),
        ),
    ]
