# Generated by Django 4.1.12 on 2023-12-01 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0006_progress_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedModules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Course.progress",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Course.video",
                    ),
                ),
            ],
        ),
    ]
