# Generated by Django 4.1.12 on 2023-12-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0008_alter_course_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="students_enrolled",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="coursedetails",
            name="articles",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coursedetails",
            name="coding_exercises",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coursedetails",
            name="hours_of_video",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="featured_review",
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name="review",
            name="star",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
