# Generated by Django 4.2.7 on 2023-12-01 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Course", "0009_alter_course_rating_alter_course_students_enrolled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="students_enrolled",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
