# Generated by Django 4.1.12 on 2023-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Userauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
